2021-03-16 12:20:17
Notice: Exception caught in H:\www\ns_vendor\Core\Lib\Router.php on line 195
Message: "home" NOT found!
{
    "Peak": "0.6979MB",
    "Memory": "0.6587MB",
    "Duration": "7.458ms",
    "Param": {
        "ip": "127.0.0.1",
        "cmd": "home/test",
        "data": [],
        "argv": ""
    },
    "Trace": [
        "NS->__construct called in H:/www/ns/app/api.php on line 27",
        "Core/Lib/Router->parse called in H:/www/ns_vendor/NS.php on line 115",
        "Core/Lib/Router->callParser called in H:/www/ns_vendor/Core/Lib/Router.php on line 112",
        "call_user_func called in H:/www/ns_vendor/Core/Lib/Router.php on line 249",
        "Core/Lib/Router->cgiParser called"
    ]
}

